#!/bin/sh
echo "=== Compiling with JavaCC ==="
./javacc-5.0/bin/javacc ./ForteLang.jj
echo "=== Compiling with Javac ==="
javac -Xlint:cast *.java
echo "=== Packaging into ForteLang.jar ==="
jar cmf ForteLang.mf ForteLang.jar *.class std.fl
echo "=== Running tests ==="
java -jar ForteLang.jar tests.fl -impure -silent