/* Generated By:JavaCC: Do not edit this line. ForteLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ForteLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 1;
  /** RegularExpression Id. */
  int FLOATING_POINT_NUMBER = 2;
  /** RegularExpression Id. */
  int BOOLEAN = 3;
  /** RegularExpression Id. */
  int OPENBRACKET = 4;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 5;
  /** RegularExpression Id. */
  int EQUALS = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int OPENCBRACKET = 8;
  /** RegularExpression Id. */
  int CLOSECBRACKET = 9;
  /** RegularExpression Id. */
  int NUM = 10;
  /** RegularExpression Id. */
  int BOO = 11;
  /** RegularExpression Id. */
  int COLON = 12;
  /** RegularExpression Id. */
  int VAR_NAME = 13;
  /** RegularExpression Id. */
  int FUNCTION_ARROW = 14;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BlockComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMBER>",
    "<FLOATING_POINT_NUMBER>",
    "<BOOLEAN>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"num\"",
    "\"bool\"",
    "\":\"",
    "<VAR_NAME>",
    "\"->\"",
    "<token of kind 15>",
    "<token of kind 16>",
    "\"#[\"",
    "\"#[\"",
    "<token of kind 19>",
    "\"]#\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
  };

}
